Repository neurobagel/annotation_tool, pull requests merged in 2022-12, with the labels that each got.

#249 Refactored annot-columns component so it's ready for the store
  components/annot-columns.vue
  cypress/component/annot-columns.cy.js
Labels: maintenance:refactor

#233 Next page accessibility/navbar/layout refactor + All page refactor
  assets/css/main.css
  components/next-page.vue
  components/tool-navbar.vue
  cypress/e2e/page/categorization-pagetests.cy.js
  cypress/support/commands.js
  layouts/default.vue
  pages/annotation.vue
  pages/categorization.vue
  pages/download.vue
  pages/index.vue
  store/index.js
Labels: categorization page, download page, annotation page, landing page, data store, feature:enhancement, maintenance:refactor

#258 Removal of nextPageAccessible getter
  components/next-page.vue
  store/index.js
Labels: global interface, feature:consolidation
